### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get' when running telescope --docker

### ISSUE THREAD

**Issue by howardyoo** [astronomer/telescope#70]
OS: macOS X
no particular version specific issue.

When running the command `telescope --docker` after installing it as instructed, the following error is observed:

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/telescope", line 8, in <module>
    sys.exit(cli())
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/telescope/__main__.py", line 158, in cli
    assemble(report, output_filepath=report_output_file, report_type=report_type)
  File "/opt/homebrew/lib/python3.9/site-packages/telescope/reporters/report.py", line 124, in assemble
    airflow_report = AirflowReport.from_input_report_row(
  File "/opt/homebrew/lib/python3.9/site-packages/telescope/reporters/__init__.py", line 138, in from_input_report_row
    task_run_info = sum_usage_stats_report_summary(input_row.get("usage_stats_report", []))
AttributeError: 'str' object has no attribute 'get'
```

- just a quick debugging revealed that the content inside "airport_report" was not in a parsed json format, but pre-parsed json string which looked like this:
```
{"docker": {"c5deb7a28a": {"airflow_report": "{\"airflow_version_report\": \"2.2.2+astro.1\", \"providers_report\": {\"apache-airflow-providers-amazon\": \"1!2.3.0\", \"apache-airflow-providers-cncf-kubernetes\": \"1!2.1.0\", \"apache-airflow-providers-elasticsearch\": \"1!2.1.0\", \"apache-airflow-providers-ftp\": \"1!2.0.1\", \"apache-airflow-providers-google\": \"1!6.1.0\", \"apache-airflow-providers-http\": \"1!2.0.1\", \"apache-airflow-providers-imap\": \"1!2.0.1\", \"apache-airflow-providers-microsoft-azure\": \"1!3.3.0\", \"apache-airflow-providers-mysql\": \"1!2.1.1\", \"apache-airflow-providers-postgres\": \"1!2.3.0\", \"apache-airflow-providers-redis\": \"1!2.0.1\", \"apache-airflow-providers-slack\": \"1!4.1.0\", \"apache-airflow-providers-sqlite\": \"1!2.0.1\", \"apache-airflow-providers-ssh\": \"1!2.3.0\"}, \"hostname_report\": \"c5deb7a28a6d\", \"installed_packages_report\": {\"zope.interface\": \"5.4.0\", \"zope.event\": \"4.5.0\", \"wtforms\": \"2.3.3\", \"wheel\": \"0.37.0\", \"werkzeug\": \"1.0.1\", \"websocket-client\": \"1.2.1\", \"wcwidth\": \"0.2.5\", \"watchtower\": \"1.0.6\", \"virtualenv\": \"20.10.0\", \"vine\": \"5.0.0\", \"urllib3\": \"1.26.7\", \"uritemplate\": \"3.0.1\", \"unicodecsv\": \"0.14.1\", \"typing-inspect\": \"0.7.1\", \"typing-extensions\": \"3.10.0.2\", \"tornado\": \"6.1\", \"text-unidecode\": \"1.3\", \"termcolor\": \"1.1.0\", \"tenacity\": \"8.0.1\", \"tabulate\": \"0.8.9\", \"swagger-ui-bundle\": \"0.0.9\", \"statsd\": \"3.3.0\", \"sshtunnel\": \"0.4.0\", \"sqlalchemy\": \"1.3.24\", \"sqlalchemy-utils\": \"0.37.9\", \"sqlalchemy-jsonfield\": \"1.0.0\", \"sniffio\": \"1.2.0\", \"slack-sdk\": \"3.11.2\", \"six\": \"1.16.0\", \"setuptools\": \"57.5.0\", \"setproctitle\": \"1.2.2\", \"s3transfer\": \"0.5.0\", \"rsa\": \"4.7.2\", \"rich\": \"10.13.0\", \"rfc3986\": \"1.5.0\", \"req
...
```

Therefore, a logic to check the type of `airflow_report` and when it is in str type, having json.loads to parse it might be required.

**Comment by fritz-astronomer** [comment]
Should be fixed in https://github.com/astronomer/telescope/commit/e6ea78826227470822d9d2b8e673e141fe2f846c
Will test more and then cut a release with other features. Thank you for your issue report!

**Comment by fritz-astronomer** [comment]
v.1.20 released!
